### ISSUE TITLE
Improve support for Hylé transactions

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/explorer#1]
Hylé transactions package several state changes and large proofs. This makes reading TXs on the explorer rather awkward.

The code should be updated to better support the multiple state changes, link to the appropriate targeted contracts, and hide the proofs behind a toggle.

**Comment by mariocodecr** [comment]
Hello everyone! 👋 I'm eager to contribute to enhancing the support for Hylé transactions within the project.

To address this issue, I'll start by analyzing the current implementation of Hylé transactions to identify areas for improvement. This will involve understanding how transactions are currently handled, including their execution, validation, and integration with other components of the project.

Based on my analysis, I'll work on improving the support for Hylé transactions by implementing enhancements or optimizations. This may include optimizing transaction execution speed, enhancing transaction validation mechanisms, or improving error handling for transaction-related processes.

Additionally, I'll ensure that any changes made are well-documented and aligned with the project's architecture and coding standards. Clear documentation will help users and developers understand how to work with Hylé transactions effectively.

Excited to contribute and make Hylé transactions even more robust and efficient!

Best regards,
Mario Araya

**Comment by Ugo-X** [comment]
Hello good afternoon, my name is Ugo and I am a full-stack developer. I have contributed to quite some projects, including previous OD hacks which you can verify from my GitHub profile. I would like to be assigned to this issue. Thank you

**Comment by wraitii** [comment]
Hey @Ugo-X , sounds good, we have a public TG here if you have questions: https://t.me/+daA5zWOJGEQ3NGE0

I think I'l assign you to this one first and then maybe #2 later

**Comment by Ugo-X** [comment]
> Hey @Ugo-X , sounds good, we have a public TG here if you have questions: https://t.me/+daA5zWOJGEQ3NGE0
> 
> I think I'l assign you to this one first and then maybe #2 later

alright thanks. I will get it done quickly and possibly handle the other one if it is up for grabs.

**Comment by Ugo-X** [comment]
Hello good afternoon @wraitii I am working on this already and i am making progress, will let you know if i encounter any issues
