### ISSUE TITLE
Improve support for Hylé contracts

### ISSUE THREAD

**Issue by wraitii** [Hyle-org/explorer#2]
- Show more information about each contract in the main contract list
- Improve the search UI, we don't really have a creator yet and the "contract" is actually the name.
- List transactions targeting a contract, potentially
- Allow parsing Base64 state digest to hex / decimal / ascii

**Comment by mariocodecr** [comment]
@wraitii  Greetings! 🌟 I'm excited to contribute to enhancing the support for Hylé contracts within the project.

To tackle this issue, I'll start by examining the existing codebase to understand how Hylé contracts are currently implemented. Then, I'll work on improving the support for Hylé contracts by enhancing their functionality, performance, or compatibility with other parts of the project.

This may involve writing new code, refactoring existing code, or updating documentation to provide clearer guidance on working with Hylé contracts. I'll ensure that any changes made are well-tested and aligned with the project's architecture and coding standards.

Excited to dive into this task and contribute to the project's success!

Warm regards,
Mario Araya

**Comment by Ugo-X** [comment]
Hello good afternoon, my name is Ugo and I am a full-stack developer. I have contributed to quite some projects, including previous OD hacks which you can verify from my GitHub profile. I would like to be assigned to this issue. Thank you

**Comment by od-hunter** [comment]
@wraitii hello, I’ll love to work on this project. This is my first time in Starknet ecosystem and I would love to proof my acquired skill, thank you.

**Comment by Ugo-X** [comment]
> Hello good afternoon, my name is Ugo and I am a full-stack developer. I have contributed to quite some projects, including previous OD hacks which you can verify from my GitHub profile. I would like to be assigned to this issue. Thank you

Please @wraitii can i be assigned this issue?

**Comment by Ugo-X** [comment]
will need a sample contract address to work on this, to see what it looks like right now so i can start modifying
